- scene_generator/scene_generator.py
Just makes the same static scene every time for now.
> MCS-80 initial scene generator

- ai2thor_wrapper/mcs_controller_ai2thor.py
- ai2thor_wrapper/mcs_object.py
- ai2thor_wrapper/test_mcs_controller_ai2thor.py
Added object metadata properties to (Python) Step Output object in AI2-THOR Controller.
> MCS-52 MCS-74 Added Object Metadata Properties

- ai2thor_wrapper/mcs_controller_ai2thor.py
- ai2thor_wrapper/run_mcs_environment.py
- ai2thor_wrapper/scenes/playroom.json
ai2thor changes here: https://github.com/NextCenturyCorporation/ai2thor/pull/9
> Testing PutObject (MCS-59), updating playroom.json.

- scene_generator/scene_generator.py
> Mcs 27 Generate Scenes with Many Different Player Starting Locations

- python_api/machine_common_sense/run_mcs_human_input.py
Changes to human input mode script:
- Added support for the `action_list` returned in the step output that restricts the available actions for the next step.
- Condensed the "help" print statements so they take up less space in the terminal.
Brian, please let me know what you think.
> Minor changes to human input mode

- python_api/machine_common_sense/run_mcs_human_input.py
Done:
- Added reset command to human input mode script.
- Fixed bug with script's optional command line arguments.
Also, should we continue doing PRs for small changes like this, or should we just push them directly into master?  I'm fine either way, I just don't know if you'd think small reviews like this are a "waste of time".
> Add Reset to Human Input Mode

- python_api/machine_common_sense/mcs_controller_ai2thor.py
- python_api/test/test_mcs_controller_ai2thor.py
Used with Unity branch MCS-108 (PR: https://github.com/NextCenturyCorporation/ai2thor/pull/17)
> MCS-108 Python API: Each action step will now return multiple images.

- python_api/API.md
- python_api/machine_common_sense/mcs_action_api_desc.py
- python_api/machine_common_sense/run_mcs_environment.py
ai2thor changes here: https://github.com/NextCenturyCorporation/ai2thor/pull/15/files
> Update ThrowObject to take a directional vector as input (MCS-50).

- scene_generator/goals.py
- scene_generator/goals_test.py
- scene_generator/scene_generator.py
* Renamed goals
* added more fields to goals (category, domain_list, description)
> MCS-114 Minor updates to Scene Gen

- scene_generator/goals.py
Retrieval goal now only selects from pickupable objects for the target.
> Added pickupable object filter

- scene_generator/goals.py
- scene_generator/goals_test.py
Draft PR awaiting MCS-145 merge.
Added Traversal goal.
> MCS-148 Added TraversalGoal with tests

- scene_generator/geometry.py
- scene_generator/geometry_test.py
- scene_generator/goals.py
- scene_generator/goals_test.py
- scene_generator/separating_axis_theorem.py
Fixes issue of object bounds being outside the room
> Mcs 157: [Critical] Bug in Scene Generator Collision Detection

- scene_generator/goals.py
- scene_generator/goals_test.py
- scene_generator/scene_generator.py
Finally got a unit test working. I would prefer more extensive testing but with the impending release more eyes on it will have to do.
> MCS-159 Prevent duplicate goal objects

- python_api/API.md
- python_api/machine_common_sense/mcs_controller_ai2thor.py
- python_api/machine_common_sense/mcs_object.py
- python_api/machine_common_sense/mcs_step_output.py
- python_api/machine_common_sense/mcs_util.py
- python_api/test/test_mcs_controller_ai2thor.py
- python_api/test/test_mcs_object.py
- python_api/test/test_mcs_util.py
- Added dimensions and new distance properties to the MCS Object class as used in the MCS AI2-THOR Controller.
- Fixed issues with Python class constructors.
> MCS-155 Added dimensions and new distance properties to MCS Object class

- scene_generator/goals.py
- scene_generator/scene_generator.py
Added a flag to the scene generator to make calculating the optimal path for interaction goals an optional behavior used for evaluation data (since I think we decided that we don't want it for our training data).
> Make Optimal Path Optional

- scene_generator/goals.py
- scene_generator/scene_generator.py
enhanced --goal to accept specific goal name
> MCS-169: Allow generating specific goal

- python_api/machine_common_sense/mcs_reward.py
- python_api/test/test_mcs_reward.py
Need eyes to ensure this is correct.
> MCS-176 Fixing transferral rewards and tests

- scene_generator/geometry.py
- scene_generator/goals.py
- scene_generator/goals_test.py
- scene_generator/pretty_json/pretty_json.py
fixed multiple bugs
* missing arguments for calc_obj_coords
* missing arg for point_within_room
* broken test for pickupable-ness and stackTarget-ness
* missing arguments to superclass method call for update_body
* JSON-ification bug
> Mcs 171: calc_obj_pos in goals.py is broken

- scene_generator/geometry.py
- scene_generator/goals.py
I accidentally merged the first PR for this before its reviews were done, so there were some other changes to make.
> Mcs 118: IntPhys Scene Generator: Occluders for Objects Moving Across (Re-merge)

- scene_generator/goals.py
- scene_generator/goals_test.py
use acceleration to check for possible collision between objects
> MCS-188: IntPhys Scene Generator: Collision

- scene_generator/goal.py
- scene_generator/goals.py
- scene_generator/intphys_goals.py
- scene_generator/scene_generator.py
Skeleton code for quartets for object permanence scenes. Merge after https://github.com/NextCenturyCorporation/MCS/pull/90
> Mcs 139: IntPhys Scene Generator: Generate Object Permanence Scene Quartets

- python_api/API.md
- python_api/machine_common_sense/mcs_controller_ai2thor.py
Please see https://github.com/NextCenturyCorporation/ai2thor/pull/33
> MCS-218 Updated the depth mask code and documentation in our Python API based on the corresponding changes in our Unity application.

- scene_generator/quartets.py
- scene_generator/scene_generator.py
- scene_generator/util.py
First phase of quartet for shape constancy. Will be completed in subsequent tickets.
> Mcs 140:  IntPhys Scene Generator: Generate Shape Constancy Scene Quartets

- python_api/API.md
- python_api/machine_common_sense/mcs_controller_ai2thor.py
- python_api/machine_common_sense/mcs_step_output.py
- python_api/test/test_mcs_controller_ai2thor.py
- python_api/test/test_mcs_step_output.py
Corresponding Unity PR:  https://github.com/NextCenturyCorporation/ai2thor/pull/34
> MCS-217 Added structural object list to step output class.

- python_api/API.md
- python_api/machine_common_sense/mcs_controller_ai2thor.py
- python_api/machine_common_sense/mcs_step_output.py
- python_api/test/test_mcs_controller_ai2thor.py
- python_api/test/test_mcs_step_output.py
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/37
> MCS-193 Added camera metadata to Step Output object in Python API

- scene_generator/pairs.py
- scene_generator/scene_generator.py
Most implementation will be in subsequent tickets/branches. This is common stuff that I expect will be used for a bunch of it.
> Mcs 235: Interaction Scenes: Generate Pairs of Scenes

- python_api/API.md
- python_api/machine_common_sense/mcs_controller_ai2thor.py
- python_api/machine_common_sense/mcs_object.py
- python_api/machine_common_sense/mcs_util.py
- python_api/test/test_mcs_controller_ai2thor.py
- python_api/test/test_mcs_object.py
- python_api/test/test_mcs_util.py
- scene_generator/objects.py
Corresponding Unity PR https://github.com/NextCenturyCorporation/ai2thor/pull/43
> MCS-258 Return Object Shape and Color in Object Metadata

- python_api/API.md
Fixes https://github.com/NextCenturyCorporation/MCS/issues/131.
> Document that `field_of_view` is vertical

- homepage/js/upload_s3_button.js
gzip files were being wrapped with extra formatting, fix so that nothing wraps the files that are being uploaded.
> MCS-289: Fix file format for upload, gzips unable to be downloaded properly

- scene_generator/scene_generator.py
Added a unique ID shared between scenes in quartets or pairs so they can be filtered in the UI.
> MCS-236 Scene Generator Quartet/Pair ID Tag

- scene_generator/intphys_goals.py
- scene_generator/intphys_goals_test.py
- scene_generator/objects.py
- scene_generator/quartets.py
- scene_generator/quartets_test.py
- Added ducks and racecars as new options to IntPhys "falling down" scenes.
- Fixed a few minor bugs with IntPhys Shape Constancy quartets.
> MCS-293 Added novel objects to IntPhys falling-down scenes.

- scene_generator/geometry.py
- scene_generator/geometry_test.py
- scene_generator/goal.py
- scene_generator/interaction_goals.py
- scene_generator/interaction_goals_test.py
- scene_generator/pairs.py
- scene_generator/pairs_test.py
- scene_generator/util.py
- scene_generator/util_test.py
In the Scene Generator:
- Fixed bugs with positioning objects.
- Added unit tests.
- Updated debug statements.
- Cleaned up variables.
> MCS-311 MCS-314 MCS-335 Scene Generator Bug Fixes and Enhancements

- homepage/index.html
- mcs_docker_setup/analysis-ui/src/components/App/addComment.jsx
- mcs_docker_setup/analysis-ui/src/components/App/commentsDisplay.jsx
- mcs_docker_setup/analysis-ui/src/components/App/evalConstants.jsx
- mcs_docker_setup/analysis-ui/src/components/App/flagCheckboxMutation.jsx
- mcs_docker_setup/analysis-ui/src/components/App/header.jsx
- mcs_docker_setup/analysis-ui/src/components/App/index.jsx
- mcs_docker_setup/analysis-ui/src/components/App/scenes.jsx
- mcs_docker_setup/analysis-ui/src/css/app.css
- mcs_docker_setup/analysis-ui/src/index.js
- mcs_docker_setup/docker-compose.yml
- mcs_docker_setup/node-graphql/server.elasticsearch.js
- mcs_docker_setup/node-graphql/server.graphql.js
- mcs_docker_setup/resources/config-staging.yaml
- mcs_docker_setup/resources/config.yaml
- mcs_docker_setup/resources/nginx.conf
This is a work in progress.  Scenes.jsx needs refactoring, but waiting to do more refactoring when we add in Interactive display hooks.
> MCS-186: UI Design for Eval2

- python_api/machine_common_sense/action.py
- python_api/machine_common_sense/run_human_input.py
- python_api/test/test_action.py
Action.SOME_ACTION.value will still return the action method name, but now Action has additional attributes for key and desc.
> Combine Action, ActionKeys and ActionDesc into one enum (MCS-352).

- machine_common_sense/controller.py
- tests/test_controller.py
Fixes the movement bug that Falk reported today on Slack.
We will also need the corresponding Unity fix:
https://github.com/NextCenturyCorporation/ai2thor/pull/92
Also added some more terminal output for human input mode.
> MCS-417 Set snapToGrid to False

- machine_common_sense/controller.py
- machine_common_sense/history_writer.py
- scripts/run_init_scenes.py
- scripts/run_interactive_samples.py
- scripts/run_just_pass.py
- scripts/run_just_rotate.py
- scripts/run_last_action.py
- scripts/run_sample_sequence.py
Added end_scene call to scripts. Also added some checks to the controller if history writing was enabled/disabled.
> MCS-420 Calling end scene in runnable scripts

- machine_common_sense/API.md
- machine_common_sense/goal_metadata.py
- Added agent goal
- Renamed intuitive physics goal
> Goal Documentation

- machine_common_sense/controller.py
- machine_common_sense/plotter.py
- machine_common_sense/uploader.py
- requirements.txt
- setup.py
Generating a topdown plot for each frame when in evaluation mode as well as creating and uploading the video of those plots.
> MCS-375 Topdown plot

- README.md
- machine_common_sense/config_manager.py
- machine_common_sense/controller.py
- machine_common_sense/plotter.py
- machine_common_sense/recorder.py
- tests/test_config_manager.py
- tests/test_plotter.py
Also fixed a couple of minor related bugs.
> MCS-423 Added config option to generate top-down videos in non-evaluation mode

- machine_common_sense/history_writer.py
- machine_common_sense/step_metadata.py
- tests/test_history_writer.py
And remove a few unnecessary outputs from them
> MCS-489: Make history files smaller 

- machine_common_sense/controller.py
- machine_common_sense/history_writer.py
- tests/test_history_writer.py
Synchronize timestamps for history and video files (MCS-506), remove timestamps for S3 upload in evaluation mode (MCS-549).
> Timestamp fixes

- machine_common_sense/serializer.py
- tests/test_serializer.py
Serializer module formatting and small unit test import fix.
> Fixing formatting

- contributing.md
- machine_common_sense/DEV.md
> Contribution and MCS Core dev guidelines for PR handling

- integration_tests/data/061.move_into_wall_large_room.actions.txt
- integration_tests/data/061.move_into_wall_large_room.level1.outputs.json
- integration_tests/data/061.move_into_wall_large_room.level2.outputs.json
- integration_tests/data/061.move_into_wall_large_room.oracle.outputs.json
- integration_tests/data/061.move_into_wall_large_room.scene.json
- integration_tests/data/062.move_into_wall_small_room.actions.txt
- integration_tests/data/062.move_into_wall_small_room.level1.outputs.json
- integration_tests/data/062.move_into_wall_small_room.level2.outputs.json
- integration_tests/data/062.move_into_wall_small_room.oracle.outputs.json
- integration_tests/data/062.move_into_wall_small_room.scene.json
- machine_common_sense/scenes/SCHEMA.md
- machine_common_sense/scenes/large_room.json
- machine_common_sense/scenes/small_room.json
Integration tests and documentation for MCS-95 which adds configuration to change the room size.
See https://github.com/NextCenturyCorporation/ai2thor/pull/118 which should be merged before this.
> Mcs 95 config room size

- integration_tests/data/065.platform.actions.txt
- integration_tests/data/065.platform.level1.outputs.json
- integration_tests/data/065.platform.level2.outputs.json
- integration_tests/data/065.platform.oracle.outputs.json
- integration_tests/data/065.platform.scene.json
- machine_common_sense/scenes/platform.json
Integration tests and scene file for pull request found at: https://github.com/NextCenturyCorporation/ai2thor/pull/123
> Mcs 472 platforms

- integration_tests/data/065.platform.scene.json
- integration_tests/data/070.open_close_container.actions.txt
- integration_tests/data/070.open_close_container.level1.outputs.json
- integration_tests/data/070.open_close_container.level2.outputs.json
- integration_tests/data/070.open_close_container.oracle.outputs.json
- integration_tests/data/070.open_close_container.scene.json
- integration_tests/run_handmade_tests.py
- machine_common_sense/API.md
- machine_common_sense/controller.py
- machine_common_sense/object_metadata.py
- machine_common_sense/scenes/container_open_close.json
- tests/test_controller.py
- tests/test_object_metadata.py
Updates to test open and close from config file by adding isOpen and openable to metadata
Added integration test to test open/close
Added new scene to show open and close
Associated with: https://github.com/NextCenturyCorporation/ai2thor/pull/131
> MCS-620 New config file property to open/close container

- machine_common_sense/API.md
- machine_common_sense/controller.py
- machine_common_sense/step_metadata.py
- tests/test_step_metadata.py
Closes #239.
Associated ai2thor change here: https://github.com/NextCenturyCorporation/ai2thor/pull/130
> MCS-441 - Add performer reach and radius to metadata

- integration_tests/data/071.pickup_container.actions.txt
- integration_tests/data/071.pickup_container.level1.outputs.json
- integration_tests/data/071.pickup_container.level2.outputs.json
- integration_tests/data/071.pickup_container.oracle.outputs.json
- integration_tests/data/071.pickup_container.scene.json
- machine_common_sense/scenes/move_contained.json
Integration tests to correspond to https://github.com/NextCenturyCorporation/ai2thor/pull/132
Note: Integration test 46 and 48 will fail until pull request in MCS 303 is merged. NextCenturyCorporation/MCS#303
> MCS-473 Fix to picking contained objects when picking up a container

- machine_common_sense/controller.py
- machine_common_sense/reward.py
- tests/test_controller.py
- tests/test_reward.py
This ticket seemed relatively simple, except we needed to push reach distance down to a goal for traversal rewards.
Associated ticket in other repo: https://github.com/NextCenturyCorporation/ai2thor/pull/135
> MCS-626 updated to move maxVisibleDistance to Unity code

- machine_common_sense/API.md
- machine_common_sense/controller.py
- machine_common_sense/step_metadata.py
- tests/test_step_metadata.py
Fixes https://github.com/NextCenturyCorporation/MCS/pull/328#issuecomment-831392038
> Remove Pillow image lists and depth data from JSON debug output files.

- machine_common_sense/controller.py
- machine_common_sense/controller_events.py
- machine_common_sense/controller_logger.py
- machine_common_sense/controller_video_manager.py
- machine_common_sense/history_writer.py
This was a fairly easy ticket so hopefully the review doesn't need to be that extensive.  
- Removed the controller from all event functions.
- Moved some constants from controller to video manager.
> removed controller from events

- machine_common_sense/__init__.py
- machine_common_sense/controller.py
- machine_common_sense/controller_events.py
- machine_common_sense/controller_logger.py
- machine_common_sense/controller_media.py
- machine_common_sense/controller_video_manager.py
- machine_common_sense/history_writer.py
- machine_common_sense/setup.py
- tests/mock_controller.py
- tests/test_mcs.py
This pull request split all the video and image creation code in to separate subscribers.  They are then subscribed depending on the config.
> Mcs 664 separate video manager

- docs/source/schema.rst
- integration_tests/additional_integration_tests.py
- integration_tests/run_handmade_tests.py
- machine_common_sense/config_manager.py
- machine_common_sense/controller.py
- machine_common_sense/controller_logger.py
- machine_common_sense/controller_media.py
- machine_common_sense/controller_output_handler.py
- machine_common_sense/goal_metadata.py
- machine_common_sense/history_writer.py
- requirements.txt
- scripts/run_human_input.py
- setup.py
- tests/test_config_manager.py
- tests/test_controller.py
- tests/test_controller_output_handler.py
- tests/test_history_writer.py
Converted SceneConfiguration into a concrete class
> Mcs 686 start scene classes

- machine_common_sense/controller.py
- machine_common_sense/controller_output_handler.py
- tests/test_controller_output_handler.py
See MCS-409 ticket for motivation here.  
Also, this ticket is somewhat hard to review as the diff doesn't put changes near each other very well.
> Mcs 409 scene event class

- .github/workflows/ci.yaml
- .github/workflows/development-merge.yaml
- .github/workflows/docs.yaml
- README.md
Added unit test, extensive unit test, and documentation to badging at the top of the README.
> MCS 679 badges

- integration_tests/data/080.pickup_chest.actions.txt
- integration_tests/data/080.pickup_chest.level1.outputs.json
- integration_tests/data/080.pickup_chest.level2.outputs.json
- integration_tests/data/080.pickup_chest.oracle.outputs.json
- integration_tests/data/080.pickup_chest.scene.json
https://github.com/NextCenturyCorporation/ai2thor/pull/148
The test is labeled 80 because I made a bunch of tests for ramp ascension that stopped at 79 that have not been merged yet
> Picking up static containers when switched to a pickupable object throws nre exception fixed integration testing

- machine_common_sense/logging_config.py
I think the solution is supposed to be this straightforward, link to the issue:
https://nextcentury.atlassian.net/browse/MCS-753?atlOrigin=eyJpIjoiZWQwMzAzMDFlYjNiNGVmNTliZWFiOTcwYzM0ZjA4NmIiLCJwIjoiaiJ9
> Automatically Create Log Folder inside /scripts if Needed

- machine_common_sense/unity_executable_provider.py
- scripts/run_human_input.py
Tiny PR to fix date handling in auto-downloader.
Also added to human input.
> fixed autodownloader.  Added version to human input

- docs/source/install.rst
- scripts/cache_addressables.py
- setup.py
Adding some documentation and instructions to cache addressables script.
> Mcs 844 cache addressables docs

- machine_common_sense/plotter.py
Changed robot nose from single pixel line to a disk.
> MCS-884 Increasing visibility of robot heading

- integration_tests/data/042.put_onto_floor.level1.outputs.json
- integration_tests/data/042.put_onto_floor.level2.outputs.json
- integration_tests/data/042.put_onto_floor.oracle.outputs.json
- integration_tests/data/047.open_and_close_with_image_coord.level1.outputs.json
- integration_tests/data/047.open_and_close_with_image_coord.level2.outputs.json
- integration_tests/data/047.open_and_close_with_image_coord.oracle.outputs.json
- machine_common_sense/action.py
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/162
> MCS-889 Replaced NOT_RECEPTACLE with NOT_INTERACTABLE in some scenarios and updated docs.

- machine_common_sense/goal_metadata.py
- machine_common_sense/serializer.py
- machine_common_sense/step_metadata.py
> Updated docs to better describe action_list usage

- machine_common_sense/history_writer.py
- machine_common_sense/scene_history.py
- machine_common_sense/step_metadata.py
- tests/test_step_metadata.py
Moved target_visibility to SceneHistory in order to avoid documentation/TA1 confusion on that attribute and to avoid serialization problems.
> Trying visibility flag in SceneHistory

- docs/source/conf.py
- docs/source/schema.rst
- integration_tests/data/069.intuitive_physics_scene_start.oracle.outputs.json
- Added descriptions for the `floorTextures` and `holes` scene properties (that Jacob added earlier this summer)
- Added base sizes for all objects
- Added new materials and linkified them
- Updated stale entries
- Removed max width on all pages
To see it yourself:
```
cd docs
make html
google-chrome _build/html/schema.html
```
Edit: Also includes integration test update for https://github.com/NextCenturyCorporation/ai2thor/pull/167
> MCS-724 Updated the JSON schema GitHub doc

- integration_tests/data/023.open_and_close_non_container.level1.outputs.json
- integration_tests/data/023.open_and_close_non_container.level2.outputs.json
- integration_tests/data/023.open_and_close_non_container.oracle.outputs.json
- integration_tests/data/091.door_open_close.actions.txt
- integration_tests/data/091.door_open_close.level1.outputs.json
- integration_tests/data/091.door_open_close.level2.outputs.json
- integration_tests/data/091.door_open_close.oracle.outputs.json
- integration_tests/data/091.door_open_close.scene.json
Not sure how to test this since it requires updates to addressables.  I temporarily hijacked the development build when i did my tests.
> Mcs 921 doors - integration tests

- machine_common_sense/history_writer.py
- requirements.txt
- setup.py
- tests/test_history_writer.py
Can also be used as a reference to fix Eval 4
> Fixing numpy serialization in history writer

- .flake8
- machine_common_sense/action.py
- machine_common_sense/config_manager.py
- machine_common_sense/controller.py
- machine_common_sense/history_writer.py
- machine_common_sense/scripts/run_human_input.py
- machine_common_sense/scripts/run_scene_with_command_file.py
- requirements.txt
- tests/test_config_manager.py
- tests/test_controller.py
- tests/test_history_event_handler.py
- tests/test_history_writer.py
Enforces python naming conventions.
> MCS-591 pep8 naming

- machine_common_sense/config_manager.py
- machine_common_sense/controller_output_handler.py
- tests/test_controller_output_handler.py
Reworked controller_output_handler's _get_step_metadata function to reduce reported complexity. Unsure how to reduce further at this time.
> MCS-952 function refactor to reduce complexity

- machine_common_sense/controller.py
Refactored this function pretty much as-is although I do not agree with the validation approach here. Why resort to a default if we are given an invalid value? Raising an exception seems more appropriate to me in that case. Providing a default if no value is given does seem like a good idea especially if we are relying on having a value for that attribute.
> MCS-951 Reduced function complexity of validate_and_convert_params

- docs/source/install.rst
- integration_tests/additional_integration_tests.py
- integration_tests/run_handmade_tests.py
- machine_common_sense/config_manager.py
- machine_common_sense/controller.py
- machine_common_sense/parameter.py
- tests/test_config_manager.py
- tests/test_controller.py
- tests/test_parameter.py
Continuous improvements to the controller by refactoring components out of that module where possible. Improved test coverage on previously untested but key functions. Found a few issues in that process but those have been addressed as part of this PR.
> MCS-668 controller refactor

- integration_tests/data/005.ball_close_pickup.oracle.outputs.json
- integration_tests/data/006.ball_far_pickup.oracle.outputs.json
- integration_tests/data/016.pickup_multiple_object.oracle.outputs.json
- integration_tests/data/019.put_onto_non_receptacle.oracle.outputs.json
- integration_tests/data/032.stacking_blocks_top_to_top.oracle.outputs.json
- integration_tests/data/034.stacking_blocks_top_to_bottom.oracle.outputs.json
- integration_tests/data/035.stacking_blocks_side_to_top_v1.oracle.outputs.json
- integration_tests/data/036.stacking_blocks_side_to_top_v2.oracle.outputs.json
- integration_tests/data/039.stacking_blocks_many.oracle.outputs.json
- integration_tests/data/042.put_onto_floor.oracle.outputs.json
- integration_tests/data/045.pickup_and_put_with_image_coord.oracle.outputs.json
- integration_tests/data/046.pickup_trophy_with_image_coord.oracle.outputs.json
- integration_tests/data/048.open_and_pickup_with_image_coord.oracle.outputs.json
- integration_tests/data/049.pickup_then_walk.oracle.outputs.json
- integration_tests/data/071.pickup_container.oracle.outputs.json
- integration_tests/data/080.pickup_chest.oracle.outputs.json
- integration_tests/data/092.seesaw_pass_rotation.level1.outputs.json
- integration_tests/data/092.seesaw_pass_rotation.level2.outputs.json
- integration_tests/data/092.seesaw_pass_rotation.oracle.outputs.json
- integration_tests/data/093.drop_rectangular_objects.actions.txt
- integration_tests/data/093.drop_rectangular_objects.level1.outputs.json
- integration_tests/data/093.drop_rectangular_objects.level2.outputs.json
- integration_tests/data/093.drop_rectangular_objects.oracle.outputs.json
- integration_tests/data/093.drop_rectangular_objects.scene.json
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/186)
These updates only change where the objects are held in the agents hand when currently holding an object. It has nothing to do with where objects get placed. They are very small float amounts but all actions and results are the same.
> Fixed holding object placement so dropping work consistently

- machine_common_sense/scripts/run_human_input.py
Update for a recently renamed action list reference.
> Small fix for human input script

- integration_tests/data/066.end_habituation.scene.json
- integration_tests/habituation_trial_counts.scene.json
- integration_tests/run_handmade_tests.py
- machine_common_sense/controller.py
- machine_common_sense/parameter.py
- tests/test_parameter.py
- Fixed the integration tests broken by PR https://github.com/NextCenturyCorporation/MCS/pull/462
- Fixed a bug in which we weren't handling numbers correctly when comparing the user's input parameters to the action restrictions (comparing numeric strings, ints, and floats).
> Fixing MCS Integration Tests

- machine_common_sense/controller_logger.py
- machine_common_sense/controller_output_handler.py
- machine_common_sense/reward.py
- machine_common_sense/step_metadata.py
- tests/test_reward.py
- tests/test_step_metadata.py
[UNITY](https://github.com/NextCenturyCorporation/ai2thor/pull/188)
> Track number of steps on lava and add a default negative reward for each step

- docs/source/install.rst
- machine_common_sense/config_manager.py
- machine_common_sense/controller_output_handler.py
- machine_common_sense/reward.py
- tests/test_reward.py
Right now the goal reward can be a float but before this change it was an int. How do we feel about it being a float if configured that way?
> Configurable reward and penalty scores

- integration_tests/data/096.pull_object.actions.txt
- integration_tests/data/096.pull_object.level1.outputs.json
- integration_tests/data/096.pull_object.level2.outputs.json
- integration_tests/data/096.pull_object.oracle.outputs.json
- integration_tests/data/096.pull_object.scene.json
- integration_tests/data/097.push_object.actions.txt
- integration_tests/data/097.push_object.level1.outputs.json
- integration_tests/data/097.push_object.level2.outputs.json
- integration_tests/data/097.push_object.oracle.outputs.json
- integration_tests/data/097.push_object.scene.json
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/192)
Even though this ticket was just to add integration tests, I felt it was necessary to change the unity code too since the input from the python API is between 0 and 1. That was too small of a force to do anything in unity so now the unity code has a force multiplier.
> Push pull integration tests

- docs/source/schema.rst
- integration_tests/data/094.platform_lips.actions.txt
- integration_tests/data/094.platform_lips.level1.outputs.json
- integration_tests/data/094.platform_lips.level2.outputs.json
- integration_tests/data/094.platform_lips.oracle.outputs.json
- integration_tests/data/094.platform_lips.scene.json
- machine_common_sense/config_manager.py
[Scene Generator ](https://github.com/NextCenturyCorporation/mcs-private/pull/127/)
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/189)
> Platform Lips Configs

- docs/source/install.rst
- machine_common_sense/reward.py
I've changed the default lava penalty to a big value. We've been talking around this for a while. I figured I'd go ahead and make the change. We can discuss any concerns as part of this PR.
> Changed default lava penalty to 100.

- .github/workflows/development-merge.yaml
- .github/workflows/docs-publish-pypi.yaml
- .github/workflows/docs-publish.yaml
- .github/workflows/master-unit-tests.yaml
- .github/workflows/pypi-publish.yaml
- README.md
This PR is partially for a check on the code and partial to debate whether we want this.
Unfortunately it seems we need to merge the code before we can fully test what it is.  Here is what I did:
- Added a new workflow to run the comprehensive unit tests when we merge into master.  This is a copy of the dev one with the branch changed to master.  There may be better ways to do this without copying, but I figured this would work fine for now.
- Removed the badge that showed the status of the unit tests for the LAST commit to ANY branch.  (I.E. if your in-progress feature branch has a commit where tests fail, our public facing badges will show failures)
- Added badge to show status of master unit tests.  This doesn't seem to work until the master workflow actually runs.
> Updating badges

- machine_common_sense/history_writer.py
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> HistoryWriter init gotcha

- integration_tests/data/096.pull_object.actions.txt
- integration_tests/data/096.pull_object.oracle.outputs.json
I reduced the pull force so the ball doesnt collide with the agent
> Fixed pull object test

- docs/source/schema.rst
- integration_tests/data/101.gaps_in_lips.actions.txt
- integration_tests/data/101.gaps_in_lips.level1.outputs.json
- integration_tests/data/101.gaps_in_lips.level2.outputs.json
- integration_tests/data/101.gaps_in_lips.oracle.outputs.json
- integration_tests/data/101.gaps_in_lips.scene.json
- machine_common_sense/config_manager.py
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/204)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/507)
[ILE](https://github.com/NextCenturyCorporation/mcs-private/pull/142)
> MCS-1176 Docs and Integration tests for gaps in lips

- docs/source/schema.rst
- integration_tests/data/105.restrict_doors.actions.txt
- integration_tests/data/105.restrict_doors.level1.outputs.json
- integration_tests/data/105.restrict_doors.level2.outputs.json
- integration_tests/data/105.restrict_doors.oracle.outputs.json
- integration_tests/data/105.restrict_doors.scene.json
- integration_tests/data/106.open_container_restrict_doors.actions.txt
- integration_tests/data/106.open_container_restrict_doors.level1.outputs.json
- integration_tests/data/106.open_container_restrict_doors.level2.outputs.json
- integration_tests/data/106.open_container_restrict_doors.oracle.outputs.json
- integration_tests/data/106.open_container_restrict_doors.scene.json
- machine_common_sense/config_manager.py
ai2thor changes: https://github.com/NextCenturyCorporation/ai2thor/pull/210
ILE: https://github.com/NextCenturyCorporation/mcs-private/pull/147
> MCS-1140 restrict open doors

- integration_tests/data/117.pickup_open_put_close_resolved_object_ids.actions.txt
- integration_tests/data/117.pickup_open_put_close_resolved_object_ids.level1.outputs.json
- integration_tests/data/117.pickup_open_put_close_resolved_object_ids.level2.outputs.json
- integration_tests/data/117.pickup_open_put_close_resolved_object_ids.oracle.outputs.json
- integration_tests/data/117.pickup_open_put_close_resolved_object_ids.scene.json
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.actions.txt
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.level1.outputs.json
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.level2.outputs.json
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.oracle.outputs.json
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.scene.json
- integration_tests/run_handmade_tests.py
- machine_common_sense/controller_output_handler.py
- machine_common_sense/step_metadata.py
- tests/test_controller_output_handler.py
- tests/test_step_metadata.py
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/218/files)
> Object IDs from image coordinates output metadata

- integration_tests/data/141.rotate_and_move_object_collide_with_performer.actions.txt
- integration_tests/data/141.rotate_and_move_object_collide_with_performer.level1.outputs.json
- integration_tests/data/141.rotate_and_move_object_collide_with_performer.level2.outputs.json
- integration_tests/data/141.rotate_and_move_object_collide_with_performer.oracle.outputs.json
- integration_tests/data/141.rotate_and_move_object_collide_with_performer.scene.json
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/236)
> Rotate and move object collides with performer

- machine_common_sense/history_writer.py
- machine_common_sense/scripts/run_human_input.py
I want to get @cedorman 's feedback to make sure it fixes all of the issues before opening this up for general review.  
I was unable to replicate the missing history on crash, but this may prevent a bunch of the crashes.  I would like to reproduce that issue and make sure that is fixed independently as well if I can.
> Mcs 1332 put object crash

- docs/source/schema.rst
- machine_common_sense/config_manager.py
- tests/test_config_manager.py
Jira: https://nextcentury.atlassian.net/browse/MCS-1138
> MCS-1138: Add Scene Option to Toggle All Lights Off or On at Specific Action Steps

- docs/source/install.rst
Fixed the docs for the top-down camera and plotter config properties. I also alphabetized the property list.
> Fixed the docs for the top-down camera and plotter config properties.

- machine_common_sense/controller.py
See https://github.com/NextCenturyCorporation/ai2thor/pull/278
> Fixed a bug with setting the topdown image output path on Macs.

- machine_common_sense/goal_metadata.py
Needed for the Seeing Leads to Knowing (a.k.a. Buckets) task.
Corresponding ILE Scene Generator PR: https://github.com/NextCenturyCorporation/mcs-private/pull/302
> MCS-1518 Added passive goal category.

- integration_tests/data/165.agent_and_performer_on_rotating_cog.oracle.outputs.json
- integration_tests/data/166.pickup_target_in_bowl_on_rotating_cog.oracle.outputs.json
This will fix the Jenkins build.
Apparently my changes to the cog prefab accidentally fixed an underlying issue (where the cog would unintentionally get rotated twice).
> Updated integration tests due to cog prefab fix.

- integration_tests/data/096.pull_object.oracle.outputs.json
- integration_tests/data/097.push_object.oracle.outputs.json
- integration_tests/data/109.soccer_ball.oracle.outputs.json
- integration_tests/data/111.tool_push.oracle.outputs.json
- integration_tests/data/115.tool_push_into_soccer_ball.oracle.outputs.json
- integration_tests/data/118.torque_rotate_move_push_resolved_object_ids.oracle.outputs.json
- integration_tests/data/139.agents_obstructed_by_object.oracle.outputs.json
- integration_tests/data/153.all_actions_on_pickupable_object_order_of_return_status.oracle.outputs.json
Required Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/287
> MCS-1497 Updated integration tests for push/pull behavioral changes.

- integration_tests/data/180.visible_ghosted_objects.oracle.outputs.json
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/301)
> MCS-1611 Correct visibility

- integration_tests/data/088.placer.oracle.outputs.json
- integration_tests/data/170.attachable_lid.oracle.outputs.json
- integration_tests/data/171.triggered_by_correct_sequence.oracle.outputs.json
- integration_tests/data/172.triggered_by_incorrect_sequence.oracle.outputs.json
- integration_tests/data/173.attachable_lid_at_angle.oracle.outputs.json
From this change in MCSConfig.cs:
{ "Custom/Materials/Magenta", new string[] { "magenta", "purple" } }, (this was changed to the next line)
{ "Custom/Materials/Magenta", new string[] { "magenta", "purple", "red" } },
> Fix for magenta unit tests

- docs/source/install.rst
- machine_common_sense/config_manager.py
- machine_common_sense/controller.py
- machine_common_sense/controller_logger.py
- machine_common_sense/reward.py
- machine_common_sense/scripts/config_level1.ini
- machine_common_sense/scripts/config_level1_debug.ini
- machine_common_sense/scripts/config_level2.ini
- machine_common_sense/scripts/config_level2_debug.ini
- machine_common_sense/scripts/config_no_debug.ini
- machine_common_sense/scripts/config_oracle.ini
- machine_common_sense/scripts/config_oracle_debug.ini
- machine_common_sense/scripts/config_with_debug.ini
- machine_common_sense/scripts/runner_script.py
- machine_common_sense/stringifier.py
- machine_common_sense/subscriber.py
- tests/test_config_manager.py
See below for details.
I'm not sure whether we should include this with code freeze (0.6.5), or wait until our 0.7.0 release. It's just a config change, but it's also low priority.
> MCS-1668 Added terminal_output option to MCS config file.

- docs/source/install.rst
- machine_common_sense/__init__.py
- machine_common_sense/config_manager.py
- tests/test_config_manager.py
First pass, seemed too simple so I feel like I missed something. No test added yet.
> MCS-1726 - added timeout

- integration_tests/data/110.tool_cannot_walk_into.oracle.outputs.json
- integration_tests/data/111.tool_push.oracle.outputs.json
- integration_tests/data/112.tool_move.oracle.outputs.json
- integration_tests/data/113.tool_torque.oracle.outputs.json
- integration_tests/data/114.tool_rotate.oracle.outputs.json
- integration_tests/data/115.tool_push_into_soccer_ball.oracle.outputs.json
- integration_tests/data/116.tool_move_into_soccer_ball.oracle.outputs.json
- integration_tests/data/141.rotate_and_move_object_collide_with_performer.oracle.outputs.json
- integration_tests/data/179.restrict_open_objects.oracle.outputs.json
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/331
Not sure why these are working on development, but not my branch, but they were easy to fix.
> MCS-1829 Fixed integration tests failing due to recent changes.

- .github/workflows/docs-publish.yaml
- docs/requirements.txt
- docs/source/requirements.txt
> MCS-1869 fixes for doc publish

- webenabled/mcsweb.py
- webenabled/templates/mcs_page.html
Added a loading spinner for when:
- The user first goes to the page and is loading the unity app for the first time
- When a scene is loaded by the user
- When actions are being processed
> MCS-1809 [Webenabled] loading spinner
