python_api/machine_common_sense/mcs_controller_ai2thor.py, python_api/machine_common_sense/mcs_goal.py
Added support for the `last_preview_phase_step` property in the `goal`.  All actions until that step will automatically run during initialization as though the player had Passed, and we return the images from all of those steps as part of the initialization output.
You can find examples in the current IntPhys sample scenes like this:
https://github.com/NextCenturyCorporation/MCS/blob/latest/python_api/scenes/intphys_energy_conservation_plausible_sample_1.json
=> MCS-51 Preview Phase

.gitignore, python_api/machine_common_sense/mcs_controller_ai2thor.py, python_api/test/test_mcs_controller_ai2thor.py
Added visibility filter in retrieve_object_list method to filter out objects not visible to the camera. Also took a whack at the gitignore file to be slightly more standard for a python project. I'm not sure what to do about the MCS files yet.
=> MCS 109 Return visible objects only

python_api/machine_common_sense/mcs_reward.py
@chrislong noticed that sympy will do the heavy lifting directly by calling polygon.distance(pt). Updated with this approach and all unit tests still pass.
=> MCS-112 Letting sympy package figure out nearest point on polygon

python_api/machine_common_sense/mcs_reward.py, python_api/test/test_mcs_reward.py, setup.py
Traversal and transferral reward calculations are now very similar to the retrieval task.
Retrieval
RAN 1080 SCENES WITH 21600 TOTAL STEPS IN 4727.9391 SECONDS
Average single step took 0.2133 seconds
Longest single step took 0.6135 seconds
Shortest single step took 0.1619 seconds
Average single scene took 4.3777 seconds
Longest single scene took 5.5090 seconds
Shortest single scene took 3.4500 seconds
Traversal
RAN 1080 SCENES WITH 21600 TOTAL STEPS IN 4872.9901 SECONDS
Average single step took 0.2198 seconds
Longest single step took 0.4485 seconds
Shortest single step took 0.1624 seconds
Average single scene took 4.5120 seconds
Longest single scene took 5.5844 seconds
Shortest single scene took 3.4575 seconds
Transferral
RAN 1080 SCENES WITH 21600 TOTAL STEPS IN 4917.1122 SECONDS
Average …
=> MCS-190 Switching from sympy to shapely for reward calculations

scene_generator/objects.py
This was blocked by MCS-227, since I needed to confirm which drawers its actually possible to see objects in without getting stuck in them. 
I think this fix was simple and straightforward, but PR-ing just in case.
=> Remove top drawer of changing table from enclosed areas list (MCS-213).

python_api/API.md, python_api/machine_common_sense/mcs_controller_ai2thor.py, python_api/test/mock_mcs_controller_ai2thor.py, python_api/test/test_mcs_controller_ai2thor.py
The Python library can now read from an optional config file and can withhold specific metadata.
Open question: Currently we read the file path from an environment variable.  Will that be OK?
=> MCS-257 Python API Config File

python_api/machine_common_sense/mcs_reward.py, python_api/test/test_mcs_reward.py
Initially, the traversal reward was relying on the ai2thor object metadata field distanceXZ. We were misinformed what the distance measure represented which turned out to be the distance from the agent to the object center. For oblong objects like a couch, the agent could be near the arm of the couch but nowhere near the center. The fix was to use the object extents and shapely distance from agent center to polygon edge like we do for the transferral reward calculation. Added tests for oblong objects on long and short sides as well as within.
=> MCS-266 Traversal reward fix

homepage/js/upload_s3_button.js
If TA1 uploads with the same file name it would over write the submission, adding the timestamp alleviates that.
=> MCS-288: Add timestamp to evaluation submission upload filename

scene_generator/quartets.py, scene_generator/quartets_test.py
Use the same object ID for the target object in implausible shape constancy scenes from the scene generator.
=> MCS-281 Shape Constancy Scene Generator Use Same Object ID

scene_generator/goal.py, scene_generator/goal_test.py, scene_generator/interaction_goals.py, scene_generator/interaction_goals_test.py, scene_generator/intphys_goals.py, scene_generator/intphys_goals_test.py, scene_generator/materials.py, scene_generator/objects.py, scene_generator/objects_test.py, scene_generator/quartets.py, scene_generator/quartets_test.py, scene_generator/scene_generator.py, scene_generator/scene_generator_test.py, scene_generator/util.py, scene_generator/util_test.py
Accomplishments:
- Scene generator tags will now identify novel colors, shapes, and combinations in object definitions.
- Scene generator object tags now differentiate between target, distractor, and other objects.
- Scene generator now lists all targets, distractors, occluders, walls, and background objects in scenes.
- Fixed the scene generator so that all IntPhys goal types may add background objects (a.k.a. "scenery"), not just gravity goals.  (This probably should have been in its own commit, but oh well.)
Apologies for the long PR.
=> MCS-201 MCS-290 MCS-294 Tags for Eval 2 IntPhys Dataset

scene_generator/goal.py, scene_generator/goal_test.py, scene_generator/interaction_goals.py, scene_generator/interaction_goals_test.py, scene_generator/util.py
- MCS-296: All InteractionGoals now have the possibility of adding 0-10 distractors to the scene.
- Created ObjectRule classes that are used by InteractionGoals to describe the number of target and distractor objects needed by the goal type, as well as how those objects are selected and positioned.
- This simplifies the code for the InteractiveGoals a lot.
- This will be very helpful for MCS-306 when each InteractionPair will have its own InteractionGoal.  Each Pair will define specific Rules (the object definition must be similar to an existing object; the object must be positioned within specific parameters; the object must be positioned inside a container; etc.) and give them to its Goal.  Hopefully it will also be easy to mix-and-match Rules to create new Pairs in the future.
=> MCS-296 Cleanup of Interactive Goals

python_api/machine_common_sense/mcs_controller_ai2thor.py
1. Remember your AWS access key ID and secret access key, or create a new one in the AWS IAM console:  https://console.aws.amazon.com/iam/home?region=us-east-1#/users
2. Create a global MCS config file:  https://github.com/NextCenturyCorporation/MCS/blob/master/python_api/API.md#config-file
3. Add the following properties to the global MCS config file (replacing `<access_key_id>`, `<secret_access_key>`, and `<ta1_performer_name>`):
```yaml
aws_access_key_id: <access_key_id>
aws_secret_access_key: <secret_access_key>
save_images_to_s3_bucket: evaluation-images
save_images_to_s3_folder: eval-2
team: <ta1_performer_name>
```
4. `pip3 install boto3`
5. Run the simulation environment with our Python library as normal.
Example image:  https://evaluation-images.s3.amazonaws.com/eval-2/thomas_play …
=> Added way to save images to S3 using global config file.

python_api/API.md, python_api/machine_common_sense/mcs_controller_ai2thor.py, python_api/machine_common_sense/mcs_goal.py, python_api/test/test_mcs_controller_ai2thor.py, python_api/test/test_mcs_goal.py, python_api/test/test_mcs_step_output.py, scene_generator/goal.py, scene_generator/interaction_goals.py, scene_generator/intphys_goals.py, scene_generator/intphys_goals_test.py, scene_generator/pairs.py, scene_generator/quartets.py, scene_generator/quartets_test.py, scene_generator/tags.py
- Moved scene generator tags from specific goals, pairs, and quartets into separate tags file.
- Added missing properties to Python MCS Goal class.
- Updated Python API documentation.
- Removed the task_list, because I don't think it's really that important.
- Minor cleanup.
=> MCS-303 Refactor Tags

scene_generator/README.md, scene_generator/containers.py, scene_generator/containers_test.py, scene_generator/geometry.py, scene_generator/geometry_test.py, scene_generator/goal.py, scene_generator/goal_test.py, scene_generator/interaction_goals.py, scene_generator/interaction_goals_test.py, scene_generator/optimal_path.py, scene_generator/pairs.py, scene_generator/pairs_test.py, scene_generator/util.py, scene_generator/util_test.py
Accomplishments:
- Added a bunch of unit tests for pairs, interactive goals, and geometry/util functions
- Fixed an issue with the geometry function that positions an object adjacent to an existing object
- Fixed an issue with finding similarly colored objects
- Fixed issues with some intermittently broken unit tests
- Removed random choices from unit tests (they will now loop over and validate all possible choices)
- Various cleanup
Outstanding:
- Pair tests sometimes fail due to known issues (usually involving object visibility)
- Some quartet and intphys goal unit tests will intermittently fail (they will be fixed in a future ticket)
=> MCS-315 Scene Generator Unit Tests: Pairs, Interactive Goals, Geometry/Util Functions

scene_generator/containers.py, scene_generator/containers_test.py, scene_generator/geometry.py, scene_generator/geometry_test.py, scene_generator/goal.py, scene_generator/goal_test.py, scene_generator/interaction_goals.py, scene_generator/interaction_goals_test.py, scene_generator/intphys_goals.py, scene_generator/intphys_goals_test.py, scene_generator/objects.py, scene_generator/objects_test.py, scene_generator/pairs.py, scene_generator/pairs_test.py, scene_generator/quartets.py, scene_generator/quartets_test.py, scene_generator/scene_generator.py, scene_generator/scene_generator_test.py, scene_generator/tags.py, scene_generator/util.py, scene_generator/util_test.py
- Split the object definition 'choose' property into multiple separate properties ('chooseMaterial', 'chooseSize', 'chooseType') to reduce redundancy in object definitions.
- Changed object definition properties from snake_case to camelCase for consistency, based on Dean's request.  (This may affect the Eval 3 UI ingest pipeline.)
- Added 'materialCategory', 'shape', 'size', and (if needed) 'color' properties to all object definitions for continuity.
- Removed 'info_string' because it ended up being redundant with 'goal_string'.
=> MCS-321 MCS-322 MCS-327 Minor Scene Generator Tasks

.gitignore, python_api/API.md, python_api/machine_common_sense/controller.py, python_api/machine_common_sense/controller_ai2thor.py, python_api/machine_common_sense/scene_history.py, python_api/machine_common_sense/util.py, python_api/requirements.txt
See updated API description below for more detail on the new parameters. 
The following will be added to the scene history: choice, confidence, violations_xy_list, internal_state. 
If a heatmap_img is set in the step function, that will be uploaded to S3 (but the appropriate AWS config file values need to be set for this to work).
=> MCS-358 - Add plausability parameters to step function

python_api/API.md, python_api/README.md, python_api/machine_common_sense/controller_ai2thor.py, python_api/machine_common_sense/goal_metadata.py, python_api/machine_common_sense/history_writer.py, python_api/machine_common_sense/mcs.py, python_api/machine_common_sense/object_metadata.py, python_api/machine_common_sense/run_human_input.py, python_api/machine_common_sense/scene_history.py, python_api/machine_common_sense/step_metadata.py, python_api/test/test_controller_ai2thor.py, python_api/test/test_history_writer.py
This code review is doing multiple things:
1.  Adds the flag for history_enabled so that a user could turn off the history file logging if wanted
2. Moves all the history file code to a new module
3. Cleans up the history txt file and makes it a proper json file
In another ticket we will add all the new fields Thomas created in the scene files to the history file.
=> MCS-383: Add History Enabled Flag

machine_common_sense/API.md, machine_common_sense/controller.py
Moving VOE prediction into a separate function. The prediction function appends attributes to the step's history item before adding it to the history writer. The current step's history item is added to the history writer on the following step or when end scene is called.
```
#loop
output = controller.step(action)
controller.make_step_prediction(confidence=1.0, ...)
#end loop
controller.end_scene()
```
A user of the package isn't forced to call make_step_prediction and will still get scene history. The prediction values (confidence etc) will be null.
```
#loop
output = controller.step(action)
#end loop
controller.end_scene()
=> MCS-411 Splitting action step into step and prediction

machine_common_sense/API.md, machine_common_sense/controller.py, machine_common_sense/goal_metadata.py, tests/test_controller.py
It looks like we are saving most of our images as PIL.Images, but rereading the original Slack comment and looking at the code, it looked like the issue here was actually that we were saving the image data specifically for target object data as a string -- Falk mentioned that a NumPy array would be acceptable so that's what I went with. 
This change wasn’t hard, but I needed to get the image generator working (or in my case, at least get around current issues well enough to generate a scene with target objects). 
In addition, I realized that this change might be more of a backwards compatibility thing. Our target objects are always going to be the same anyway for Eval 3, and I’m not even sure we’re going to need to save the information for the target objects the same way we used to going …
=> Make sure image data is an array and not a string (MCS-405).

machine_common_sense/controller.py, tests/mock_controller.py, tests/test_env_variables.py
Can't tackle all the config changes for MCS-410, but this should address what we need for Eval 3:
- Moving config path environment variable check to controller initialization to help ensure it is set the way we want per run
- Also adding a MCS_METADATA_LEVEL override to initialization. This will be prioritized over whatever level is in the configuration file. 
I'm hoping this is good enough, but again, may need to be tweaked a bit later since we haven't fully nailed down what the automation pipeline will look like.
=> Update for setting config path + metadata properties

README.md, machine_common_sense/API.md, machine_common_sense/controller.py, machine_common_sense/mcs.py, machine_common_sense/step_metadata.py, scripts/run_human_input.py, scripts/run_init_scenes.py, scripts/run_interactive_samples.py, scripts/run_just_pass.py, scripts/run_just_rotate.py, scripts/run_last_action.py, tests/mock_controller.py, tests/test_controller.py, tests/test_step_metadata.py
Updated anywhere in confluence I could find us referencing depth_masks or depth masks as well.
=> MCS-421: Rename depth masks to depth maps

machine_common_sense/history_writer.py
After team discussions.  We will not change the code for the reward calculation, the id will still come from the goal id, but updated the target image code check to make sure we cover the cases Thomas noted in the ticket.
=> MCS-416: Fix target image check, but not updating goal id check

machine_common_sense/controller.py, machine_common_sense/history_writer.py, tests/test_history_writer.py
Scene history now creates a subfolder with the prefix name and puts the scene history files in that folder collection. Video output for evaluation purposes are written in the same folder as the debug image and upload properly to S3.
=> MCS-426 Handling scene name prefix for history, video writing and uploading

machine_common_sense/controller.py
Fix for debug mode in terminal/mcs_output files -- should only have the amount of data specified by the current metadata tier, instead of always showing the 'oracle' level. 
Not that I only changed mcs_output files, left ai2thor debug files alone since we don't restrict any output until we get to the Python API.
=> Making sure output is restricted before writing debug files.

machine_common_sense/controller.py, machine_common_sense/history_writer.py, tests/test_history_writer.py
Using this property in names for uploaded files. 
I also added metadata_tier to the filenames because I thought that was helpful, but I can take that out.
Evaluation name + metadata are first in the filenames, but I can change the ordering in case we want to keep the team name first.
Example file name: Eval3_level1_ra_playroom_visual_20201104-202325.mp4
=> MCS-427 - Add evaluation_name property to config

machine_common_sense/controller.py
Fixed a bug in which the positive reward wasn't being properly added at restricted metadata levels (like level 1 and level 2). (Apparently we need better test coverage for these metadata levels...)
See https://machinecommonsense.slack.com/archives/CTR31V12M/p1607126814291400
=> Fixed bug with reward at restricted metadata levels.

machine_common_sense/controller.py
When 'evaluation' is missing from the config (likely a non-existent config file), the key is missing from the dictionary and causes a key error. Although we use the dictionary getter everywhere else, this one slipped by.
=> Use config dict getter with default

machine_common_sense/controller.py, machine_common_sense/object_metadata.py, machine_common_sense/util.py, tests/test_controller.py, tests/test_object_metadata.py, tests/test_util.py
This is from @ThomasSchellenbergNextCentury's PR https://github.com/NextCenturyCorporation/MCS/pull/219 (cherry picked the commit + made another branch because of wonky commit history due to recent merges -- I'll copy/paste his comments): 
"Read scripted object-specific states from the scene configuration files at each step and return a state_list in the ObjectMetadata.
Lets us show when a gravity support pole is "active" or "inactive", and is flexible in case we need to give new states to objects in future tasks."
=> MCS-477 Read scripted object states from scene configuration files and return them in step output object metadata

README.md, machine_common_sense/DEV.md
Updated main MCS README to link to other public MCS GitHub repositories. (Other minor cleanup too, including adding a table of content.)
=> Updated README

machine_common_sense/API.md, machine_common_sense/controller.py
Added NumpyAwareEncoder override class to fix an issue with passing numpy arrays to Unity.
@bzinberg @fplk Can you please verify that this branch fixes the numpy array issue for you? I'll also add some new tests as part of my current [integration testing](https://github.com/NextCenturyCorporation/MCS/pull/225) ticket.
=> NumpyAwareEncoder Class Monkey Patch

machine_common_sense/API.md, machine_common_sense/controller.py, tests/mock_controller.py, tests/test_controller.py
This was to take care of logs that weren't getting saved/uploaded when the software crashed.
=> Adding atexit to always call end_scene (MCS-479).

machine_common_sense/mcs.py
In mcs.py, there is code that times out after 60 seconds when starting up the controller.  On Amazon EC2, the machines can be quite slow at the beginning which results in time out of the Unity code, producing an error that looks like:
Output: Exception in create_controller() Time out!
Based on experiments using the MESS code and p2.xlarge machines, 3 minutes is about the right amount of time.
=> Increase timeout to 3 minutes

setup.py
Although a pinned msgpack dependency was correctly added to the requirements.txt file, we missed the fact that this package dependency also needs to be added to the setup.py 'install_requires'. This is needed for researchers writing with the MCS package who aren't core developers or contributors.
=> Adding msgpack to setup dependency

machine_common_sense/recorder.py
Closes #279 by removing the ffmpeg requirement entirely. We'll do the encoding during ingest instead.
=> Removing ffmpeg video conversion from recorder

CPU_Container.dockerfile, Dockerfile
I don't think the current Dockerfile update could work. You currently do
```
ARG mcsversion=0.4.1.1
ADD https://github.com/NextCenturyCorporation/MCS/releases/download/${mcsversion}/MCS-AI2-THOR-Unity-App-v${mcsversion}.x86_64 /mcs
```
but the first occurrence of `mcsversion` should have a minus instead of a last dot. Thus, I think that URL is invalid. This PR incorporates the minus at the right location. I have not extensively tested it beyond building, but it seems more correct than the current version. Another advantage is that the PR parameterizes the library version and also makes the CPU and GPU image more consistent, since currently one puts MCS into root ant the other into `/mcs`.
Or put another way: https://github.com/NextCenturyCorporation/MCS/releases/download/0.4.1.1/MCS-AI2-TH …
=> Updated images to 0.4.1.1

integration_tests/data/046.pickup_trophy_with_image_coord.oracle.outputs.json, integration_tests/data/048.open_and_pickup_with_image_coord.oracle.outputs.json
Recent change to MCSConfig changes the colors of a material.  Integration tests needed to be updated.
See https://github.com/NextCenturyCorporation/ai2thor/commit/059752e56b8206d933b99134871f384a1e98cbcd#diff-b3da131896b6ba5b5cf33d381fb452db135e166cf128d148b5d7e6c58a2e7377   Line 24 -> 27
=> fixed integration tests after material change in MCSConfig.cs

README.md, machine_common_sense/API.md, machine_common_sense/DEV.md, machine_common_sense/config_manager.py, machine_common_sense/controller.py, machine_common_sense/step_metadata.py, tests/test_config_manager.py, tests/test_controller.py
- Adding a way to access the current metadata level from the controller
- Updated the empty string/not specified metadata level to 'default'
- Updated documentation to indicate that 'default' is meant as a developer convenience feature only, and to be clearer about what's returned for what metadata level in StepMetadata. 
Should address https://github.com/NextCenturyCorporation/MCS/issues/233 and https://github.com/NextCenturyCorporation/MCS/issues/234
=> Add metadata accessor, update documentation

integration_tests/data/073.trophy_reward.actions.txt, integration_tests/data/073.trophy_reward.level1.outputs.json, integration_tests/data/073.trophy_reward.level2.outputs.json, integration_tests/data/073.trophy_reward.oracle.outputs.json, integration_tests/data/073.trophy_reward.scene.json, machine_common_sense/controller.py, tests/test_controller.py
Added restrict goal code back in.  
Verified reward is correctly calculated (and added test for this).
Verified overhead video still shows star over goal even on metadata level 1 and level 2.
=> Mcs 622 restrict goal

.gitignore, README.md, logs/.dir, machine_common_sense/__init__.py, machine_common_sense/util.py, scripts/log.config.py, scripts/run_human_input.py
This is a possible method for us to initialize logging for local scripts.  Comments and suggests are strongly encouraged.
My goals were:
- Minimal, easy changes to any script to add logging that could be consistent
- Allow for developer to make custom changes that wouldn't be checked into git without code changes
- A reasonable default for anyone who doesn't want to mess with logging configuration
One issue: it will errors without an obvious message if the ./logs folder doesn't exist.  We could use ./ but I'd rather not let it throw a couple log files into the root directory.
=> sample logging config initialization

machine_common_sense/API.md, machine_common_sense/controller.py, machine_common_sense/goal_metadata.py, machine_common_sense/step_metadata.py, scripts/run_action_file.py, scripts/run_human_input.py, scripts/run_last_action.py, scripts/run_passive_scenes.py, tests/test_controller.py
Fixes https://github.com/NextCenturyCorporation/MCS/issues/307
Changes:
- Both GoalMetadata.action_list and StepMetadata.action_list now save actions and parameters as tuples rather than strings.
- Added "auto" mode to human input run script that automatically runs the next step if only one action is available.
- Reordered terminal output in human input run script to be more useful.
- Updated python run scripts and documentation.
TBD:
- Consider releasing a new python version.
- Post on Confluence about these changes.
=> MCS-630 Unified action list format to always use tuples and updated human input mode script.

logs/.dir, logs/.gitignore
Empty folders can't be committed to git repositories without containing at least a single file. While the `.dir` file suffices for that purpose, it does not ensure that additional log files aren't committed to the repo. However, by replacing the `.dir` file with a `.gitignore` file, we can avoid accidental committal of log files while also serving as a single file inside a folder.
=> Using gitignore file for empty logs folder

machine_common_sense/controller.py, machine_common_sense/plotter.py, machine_common_sense/recorder.py, tests/test_plotter.py, tests/test_recorder.py
The video recorder now establishes a size (width, height) from the first provided frame. All future video frames are compared against that established size and a ValueError is raises if the size varies in any dimension. The plotter naturally produces images sizes of 640x480 for the default DPI setting which is different from our rendered frames of 600x400.
=> MCS-641 natural plot sizes

integration_tests/run_handmade_tests.py, machine_common_sense/__init__.py, machine_common_sense/controller.py
Blame @ThomasSchellenbergNextCentury for this being a smaller, easy PR.
Thanks @ThomasSchellenbergNextCentury for pointing out to me that the controller is constructed in __init__
This change mostly just sets a precedent for later for using dependency injection.
=> MCS-666 moved subscriber initialization outside of the controller

.github/workflows/ci.yaml, .github/workflows/development-merge.yaml
Excluding development and master branches from the CI workflow. For development, we should run the extended python version matrix and then come up with a different set of rules when merging with master or performing a release.
=> Refine GitHub actions

machine_common_sense/controller.py, machine_common_sense/history_writer.py
Fixed error in history writer where if the writer isn't initiated (because the scene was never started) it would throw an error and crash.
The further question is should we alert the user if they do this?  Trying to end a scene when one has never started is a user error, should we detect it and alert them?  currently, there is no output and nothing happens when end_scene() is called.  stop_simulation() closes the unity window.
=> MCS-685 removed error when ending scene without starting a scene

machine_common_sense/controller.py, machine_common_sense/controller_events.py, machine_common_sense/history_writer.py
All controller events have their own specific data payload class.
I'm not sure this is a huge improvement, but at least subscribers should know what data is available.
=> Mcs 663 payload classes

machine_common_sense/controller_logger.py, machine_common_sense/controller_output_handler.py, machine_common_sense/recorder.py, tests/test_recorder.py
This is a small update to make some of the json writing threaded.
It be nice to thread the debug log file writer, but it creates a json string in a custom way.  We could create yet another record to just write text?
=> MCS-640 moved ai2thor json writing to recorder

.github/master-merge.yaml
This PR will add a master-merge.yaml workflow.  This workflow will kick off only when code is merged into master.  It will perform one last run of tests, but those tests are only on ubuntu, python version 3.6.  This choice is rather arbitrary, but I wanted only 1 instance and all the code should have already been tested when moved to development.  After the tests, a wheel file is created and a new pre-release is created.  The pre release includes the wheel file and a source tar.gz file and is tagged as latest.  
We still need to manually add the unity build, edit the version, and change the tag if necessary.  
There is an alternative method to do this where we trigger on a new tag that is semantically versioned.  I mistakenly told standup that we were not semantically versioned, but I …
=> MCS-682 add wheel file

machine_common_sense/config_manager.py
- Added debug and UI properties to the schema classes
- Marked debug and UI properties with comments
Note that this change is NOT backwards compatible, but since the issue only affects debug scene files, hopefully that limitation won't matter very much.
You can generate example scenes on your own, but here's a set that I used for my testing: https://ta2-examples.s3.amazonaws.com/mcs700_scenes.zip
Run example (from the MCS repo's root folder):
```
python scripts/run_passive_scenes.py --mcs_unity_build_file <path_to_unity_app> <path>/mcs700_0001_
```
Corresponding python PR: https://github.com/NextCenturyCorporation/mcs-private/pull/32
Corresponding ingest PR: TODO (probably when I return from vacation)
=> MCS-700 Added debug scene and object properties to the schema classes.

setup.py
Replace pinned marshmallow dependency (3.12.1) in the MCS package setup.py with any version equal to or above 3.5.2 to allow more flexibility with other packages. V3.5.2 was chosen out of the marshmallow changelog for its processing of lists of nested fields and bug fixes. MCS Developers should continue to use 3.12.1 pinned in requirements.txt.
https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#352-2020-04-30
=> Dropped minimum version of marshmallow dependency

scripts/README.md, scripts/run_interactive_scenes.py, scripts/run_passive_scenes.py, scripts/run_reorientation_scenes.py, scripts/runner_script.py
By default, scripts like `run_last_action.py` save output data named using the input scene's `name` property. For example, a scene with `"name": "thomas_1"` would generate an output folder named `thomas_1/` and, with the `--save-videos` flag, an output video named `thomas_1.mp4`
The `--prefix` flag lets you add a prefix to these output files, so, in the above example, `--prefix foobar` would generate an output folder named `foobar_thomas_1` and an output video named `foobar_thomas_1.mp4`
This is useful in the pipeline to append evaluation names and team names to the output videos uploaded to S3.
=> Added the optional prefix argument to the developer run scripts that appends a prefix to the output filenames

machine_common_sense/config_manager.py
You can test this with the validation datasets:
- https://evaluation-training-scenes.s3.amazonaws.com/eval3/eval_3_validation.zip
- https://eval-3-data.s3.amazonaws.com/eval_3_5_validation.zip
=> MCS-761 Added marshmallow scene file schema properties to enable Eval 3 and 3.5 backwards compatibility.

requirements.txt
Removing packages from requirements.txt that were likely capture early in the project with a `pip freeze > requirements.txt`. 
Destroyed my current virtual environment and remade a new one with these reqs. Unit tests and integration tests all passed still.
https://nextcenturycorporation.github.io/MCS/dev.html#package-installation
```
(mcs) MCS $ deactivate
MCS $ rm -rf venv
MCS $ python3.6 -m venv --prompt mcs venv
MCS $ source venv/bin/activate
(mcs) MCS $ python -m pip install --upgrade pip setuptools wheel
(mcs) MCS $ python -m pip install -r requirements.txt
(mcs) MCS $ python -m pip install -e .
```
=> Mcs 699 prune reqs

README.md
Trying to make clear that the dev should leverage either traditional Python OR Anaconda Python when setting up a virtual environment.
=> Updating python distribution instructions

integration_tests/integration_test_utils.py, integration_tests/run_handmade_tests.py, integration_tests/run_tests.py, machine_common_sense/unity_executable_provider.py, scripts/runner_script.py
Added develop option (or dev or development) for version for auto-downloader
Added ability to set mcs-unity-version for auto-downloader for integration test scripts and AbstractScriptRunner scripts.  More can be added as needed.
=> Mcs 797 auto download dev

docs/source/dev.rst, docs/source/install.rst
Since (I'm assuming) any users may want to enable logging, I moved the logging section of the documentation from the `dev` file (that is specifically for "package developers") to the `install` file (for general installation and setup instructions).
Would probably be good to merge this before releasing 0.4.4, unless there are any major concerns.
=> Moved logging doc section from package developer file to general install and setup file

machine_common_sense/controller.py, machine_common_sense/controller_events.py, machine_common_sense/goal_metadata.py, machine_common_sense/history_writer.py, machine_common_sense/scene_history.py, tests/test_controller.py, tests/test_history_event_handler.py
Need to wait for input from @deanwetherby on the TODOs (whether or not to get rid of make_step_prediction/if we'd like to maintain backwards compatibility, as well as anything we'd like to rename that could affect ingest). 
Spent the most time with unit tests here/trying to mock things with events. The test_history_event_handler.py may have been overkill in hindsight.
=> MCS-513 (WIP for retrospective reporting)

machine_common_sense/controller_media.py, machine_common_sense/plotter.py
Changes:
- Previously, the room's walls would not always appear in the top-down videos because they're positioned outside the room bounds. For example, in a default room (X=[-5, 5], Z=[-5, 5]), the front wall's Z position is between 5 and 6. Now, I added a buffer to the X and Z scales so the walls would be shown properly.
- I reduced the size of the room walls so they don't take up as much real estate in the top-down videos.
Here are some examples of an 8x12 room with three blue walls and one red wall.
OLD (you can barely see the right wall, and can't even see the left wall!):
NEW:
=> MCS-863 Ensure outer walls are shown properly in top-down videos.

machine_common_sense/config_manager.py, machine_common_sense/controller.py, machine_common_sense/controller_logger.py, machine_common_sense/controller_media.py, machine_common_sense/controller_output_handler.py, machine_common_sense/history_writer.py, scripts/generate_passive_quartet_videos.py, scripts/run_init_scenes.py, tests/mock_controller.py, tests/test_config_manager.py, tests/test_controller.py, tests/test_controller_output_handler.py
Removed environment variables for metadata tier and references to an outdated debug level one, so now we just have an environment variable for the config file (MCS-839). 
Also made enums for metadata tier values (MCS-476). Still questioning the value add at this point for the metadata tier enums (its still a string value anyway in the config file itself + represented as so in the logging and get_metadata_level() controller function), but let me know what you think.
=> Enum and env var fixes

scripts/runner_script.py
Example incorrect usage:
```
python3 scripts/run_passive_scenes.py --mcs_unity_build_file ~/Development/darpa/ai2thor/unity/MCS-AI2-THOR-Unity-App-v0.4.4.x86_64 docs/source/scenes/agents_preference_expected.json 
Loaded provided logging config dictionary
Found 0 files matching docs/source/scenes/agents_preference_expected.json*_debug.json
No matching files found... trying non-debug files
Found 0 files matching docs/source/scenes/agents_preference_expected.json*.json
No matching files found... Exiting
```
Example correct usage:
```
python3 scripts/run_passive_scenes.py --mcs_unity_build_file ~/Development/darpa/ai2thor/unity/MCS-AI2-THOR-Unity-App-v0.4.4.x86_64 docs/source/scenes/agents_preference_
Loaded provided logging config dictionary
Found 0 files matching …
```
=> Exit the developer run script immediately if no scene files were found.

integration_tests/additional_integration_tests.py, machine_common_sense/controller_output_handler.py, machine_common_sense/object_metadata.py, machine_common_sense/serializer.py, tests/test_controller_output_handler.py, tests/test_object_metadata.py, tests/test_serializer.py
Simply renaming 'color' to 'segment_id' in ObjectMetadata. Contrasts with other branch/PR which moves segmentation color to higher level StepMetadata.
=> MCS-318 Rename color field

machine_common_sense/history_writer.py, machine_common_sense/scene_history.py, machine_common_sense/step_metadata.py, tests/test_step_metadata.py
For one of the scorecard values, we need to know whether or not the target is visible.  Add this to the step metadata output.  This means a change to the step metadata object, _init__, and __iter__, and associated unit test.   
The determination of whether or not the target is visible is done in history_writer.  It's not clear that this is the right place for the logic, but there are other manipulations for of the step metadata and it was the easiest place to put it.
=> Mcs 909 write target visibility

requirements.txt
In addition to the changes in the [last pull request](https://github.com/NextCenturyCorporation/MCS/pull/430/files), we also need also upgrade scikit-image and numpy for this merge to build properly.
=> MCS-1005-Bumping versions of scikit-image and numpy for python 3.9 compatibility

.github/workflows/ci.yaml, .github/workflows/development-merge.yaml, .gitignore, requirements.txt, setup.py
Package dependencies all install properly. Integration tests pass. Unit tests pass albeit with numpy deprecation warnings with our new numpy-aware serialization.
(mcs-p310) MCS $ python -m unittest
............................................................................................................/home/dwetherby/workspace/MCS/tests/test_history_writer.py:242: DeprecationWarning: np.int is a deprecated alias for the builtin int. To silence this warning, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: NumPy 1.20.0 …
=> Adding support for Python 3.10

integration_tests/run_handmade_tests.py
Uses `only_test_name` to search FUNCTION_LIST in additional tests such as "depth_and_segmentation" or just "depth" for that matter. Allows developers to target these tests as well as the numbered tests.
=> Run specific additional integration test

machine_common_sense/scripts/run_human_input.py
Adding getch to the MCS package init places that module within the auto-documentation path which I am not in favor of. The best way to handle this in my opinion is with try/except ImportError.
=> Two ways of importing getch module

docs/source/scenes/container_open_close.json, docs/source/scenes/playroom.json, machine_common_sense/controller.py
Hopefully my explanation makes sense: There was a weird edge case where we were deleting/attempting to delete all files within the directory from which a run is attempted. 
This ended up being an issue with not being able to determine a scene name -- generally, if we're saving debug files, we delete all the old local versions of debug files if we're running a scene multiple times so we can save the new versions without issue, and we look for those files in a directory like `./(scene_name)`. In this case, the scene file had no scene name and the code couldn't parse it properly from the path given, so it was blank, and therefore a delete was attempted in the current directory (in this case, machine_common_sense/scripts). I added a `name` for the problematic scenes in the docs and decided to …
=> MCS-1071 - bug fix for files being deleted incorrectly with --saveVideo flag enabled

machine_common_sense/goal_metadata.py, tests/test_controller.py, tests/test_controller_output_handler.py, tests/test_goal_metadata.py
- Removed EndHabituation from the default `action_list`. EndHabituation should only be an allowable action if it's been specifically demanded for that step via the `action_list` in the scene file.
- Fixed `action_list` to always return data as tuples. Previously it might return actions and parameters as single comma-separated strings like `EndHabituation,xPosition=0,zPosition=0,yRotation=90` if they were depicted that way in the scene file (but the two should be interchangeable).
=> MCS-933 Updates to action_list

integration_tests/data/091.door_open_close.actions.txt, integration_tests/data/091.door_open_close.level1.outputs.json, integration_tests/data/091.door_open_close.level2.outputs.json, integration_tests/data/091.door_open_close.oracle.outputs.json
[Unity PR](https://github.com/NextCenturyCorporation/ai2thor/pull/185)
For some reason test 091 was inconsistent saying the door was visible on oracle output. Only happened sometimes when running all of the tests. This a quick fix to get rid of that because the action was still successful regardless.
=> Seesaw bug fix needs an integration test update for door closing

integration_tests/data/066.end_habituation.scene.json, integration_tests/habituation_trial_counts.scene.json, integration_tests/run_handmade_tests.py, machine_common_sense/controller.py, machine_common_sense/controller_logger.py, machine_common_sense/controller_output_handler.py, machine_common_sense/parameter.py, machine_common_sense/scripts/run_human_input.py, machine_common_sense/step_metadata.py, tests/test_parameter.py, tests/test_step_metadata.py
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/187)
Haptic feedback is currently an array of strings derived from an enum inside unity. The array has potential to be like ["LAVA", "UNDER_WATER"....] if we add more feedbacks. We could change the LAVA output to IN_LAVA or something like that too. Integration tests could be made too once we decide on how this should work.
=> Haptic feedback step output

machine_common_sense/action.py, machine_common_sense/controller.py, machine_common_sense/parameter.py, tests/test_action.py, tests/test_controller.py, tests/test_parameter.py
For our "force" actions (pull, push, and throw), the "force" input argument is intended to be a percentage from 0 to 1. We then multiply this force by the actual maximum force (in Newtons, I think) that we want to allow the robot to be able to apply in the Unity world. Since TA1 users would likely have no concept of what force values are useful in Unity, asking them to provide a simple percentage seemed more user-friendly than asking them to provide a value in Newtons (or whatever). I'm not tied to this approach, so I'm fine if we want to change it, but we'd need to update the documentation as well as the input parameter validation code.
Please note that while the previous max force was 50, that value was chosen somewhat arbitrarily, so I increased it to 250 in order to make tool pushing …
=> MCS-1131 Fixed action push parameter so it works as described in the API

machine_common_sense/plotter.py, tests/test_plotter.py
I was getting the following error when trying to generate top-down plots during a run:
```
Error in event with type=EventType.ON_START_SCENE to subscriber=<class 'machine_common_sense.controller_media.TopdownVideoEventHandler'>
Traceback (most recent call last):
File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller.py", line 507, in _publish_event
subscriber.on_event(event_type, payload)
File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller_events.py", line 127, in on_event
self._switcher.get(
File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller_media.py", line 177, in on_start_scene
self.save_video_for_step(payload)
File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/control …
```
=> MCS-1159 Fixed SceneCoord error in top-down plotter.

machine_common_sense/config_manager.py, tests/test_config_manager.py
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/198
Impulse force will be useful for throwing the soccer ball in the "moving target" task, and possibly other tasks in the future.
=> MCS-1160 Added option for impulse force to MCS object config schema (Python)

docs/source/dev.rst, machine_common_sense/plotter.py
Created an easier way to read in a scene and visualize a plot by making a driver main in the plotter module. This could go in the machine_common_sense/scripts folder along with the runner approach but seemed excessive for what this is trying to do.
=> MCS-1154 TopDownPlotter driver

README.md, docs/source/examples.rst, docs/source/install.rst, docs/source/remotely.rst, integration_tests/additional_integration_tests.py, integration_tests/run_handmade_tests.py, machine_common_sense/__init__.py, machine_common_sense/scripts/run_human_input.py, machine_common_sense/scripts/run_init_scenes.py, machine_common_sense/scripts/run_scene_timer.py, machine_common_sense/scripts/run_scene_with_command_file.py, machine_common_sense/scripts/runner_script.py, scripts/generate_passive_quartet_videos.py, tests/test_mcs.py
Relying on exceptions per previous conversations rather than relying on status strings in the event that something unexpected happens.
Former
`scene_data, status = mcs.load_json_scene_file('playroom.json')`
New
`scene_data = mcs.load_json_scene_file('playroom.json')`
New approach will properly raise a ValueError when the json scene file can't be properly parsed and a FileNotFoundError if the file itself can't be found. This is more descriptive than string parsing including additional possible exceptions raised by the json library and open function call.
=> MCS-1179 Removed status from json loading

docs/source/install.rst, machine_common_sense/action.py, machine_common_sense/config_manager.py, machine_common_sense/controller.py, machine_common_sense/controller_output_handler.py, machine_common_sense/goal_metadata.py, tests/test_goal_metadata.py, tests/test_step_metadata.py
Add a config for the maximum number of steps allowed on lava.  The default is 0.  If the user exceeds the maximum allowable steps, the only option is to end the scene.
=> MCS-1164: End Scene if too many steps in Lava

machine_common_sense/config_manager.py, machine_common_sense/controller.py, machine_common_sense/controller_media.py, machine_common_sense/controller_output_handler.py, machine_common_sense/step_metadata.py, machine_common_sense/stringifier.py, tests/test_controller_output_handler.py
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/205
My method of testing:
1. Do a debug run of a scene using the development Unity build: `python machine_common_sense/scripts/run_just_pass.py <json_file> --last_step 1 --debug --oracle --mcs_unity_version development`
2. The debug run creates a new folder with the scene's name. Review and backup the `mcs_output` data, which contains a `depth_map_list`, as well as the `depth_map` image.
3. Do a debug run of the same scene using the MCS-1142 Unity build: `python machine_common_sense/scripts/run_just_pass.py <json_file> --last_step 1 --debug --oracle --mcs_unity_build_file <unity_build>`
4. Compare the new `mcs_output` data and `depth_map` image with the old ones.
Here's a "huge room" scene you can use for …
=> MCS-1142 Increase Depth Map Range and Precision

integration_tests/data/069.intuitive_physics_scene_start.actions.txt, integration_tests/data/069.intuitive_physics_scene_start.level1.outputs.json, integration_tests/data/069.intuitive_physics_scene_start.level2.outputs.json, integration_tests/data/069.intuitive_physics_scene_start.oracle.outputs.json, integration_tests/data/069.intuitive_physics_scene_start.scene.json
Update related to the recent bug with passive scenes I mentioned this morning (belatedly made a ticket here: https://nextcentury.atlassian.net/browse/MCS-1239)
Thomas brought up the fair point on the Unity PR that the integration tests should've caught this. It didn't because our integration test passive scene was empty and only had one frame (this error in particular didn't result in Unity closing and you could still "Pass", but the frames just never updated properly after the first one). I added a moving occluder to the passive scene test (069) so that if something like this happens again, the test should fail. Note that this should pass with the recent ai2thor development build, but will fail (correctly) against 0.5.1.
=> Update test for passive scene to better catch issues in the future.

machine_common_sense/history_writer.py, tests/test_history_writer.py
Saving the target position at each step to the history file, which is needed for the scorecard to account for tasks with moving targets where their original position may be incorrect. 
Associated ingest/scorecard PR here: https://github.com/NextCenturyCorporation/mcs-ingest/pull/75
=> MCS-960 save target position per step

machine_common_sense/scripts/cache_addressables.py
Jed wanted a script to run to download the proper unity build and then run cache addressables.  I figured this should be easy.  Additionally, maybe this is what we should have been doing, but never really thought about since cache_addressables was created prior to the auto downloader.
This was easy enough to just do the work and debate whether it is warranted in the PR.  We can easily delete if we don't want to do this.
Reference to conversation in with Jed:
https://machinecommonsense.slack.com/archives/CTR31V12M/p1648766818248429?thread_ts=1648692973.586849&cid=CTR31V12M
=> changed cache addressables to use the auto-downloader when build path isn't provided

machine_common_sense/config_manager.py
This is needed because the ILE uses none in Vector3d to indicate use default.
=> updates to fix ILE issues

machine_common_sense/history_writer.py
Thread here along with run scripts to replicate on development: https://machinecommonsense.slack.com/archives/CTR31V12M/p1649208125675129
Fix turned out to be pretty easy. This happens when running multiple scenes in succession (originally I just fixed the original logged error with the object_list, but it turns out it after that it was writing the previous scene file's last history item to the new scene's history file). Wouldn't be an issue during evals since we run one at a time.
=> MCS-1293 - Bug fix for Slack Issue

machine_common_sense/history_writer.py
This work rounds all the float values in the history file just before writing.  It should be tested in ingest, but I've been unable to figure out how to test ingest based on the readme.  `python mcs_scene_ingest.py --folder <folder> --eval_name <name>` was not working for me.
=> Round all floats in history

docs/source/dev.rst, machine_common_sense/controller_media.py, machine_common_sense/stringifier.py, tests/test_controller_media.py, tests/test_stringifier.py
Here's my stab at improving the visibility in the debug depth images. Open to discussion and ideas for alternative approaches. Note that you'll need this fix: https://github.com/NextCenturyCorporation/ai2thor/pull/242 (Or temporarily hard-code the `clipping_plane_far` to `150.0`)
- Changed images from greyscale to RGB (technically they're HSV but then saved as RGB)
- Added 400 color bands across the camera's entire visibility range (from `0` to `150`). Each individual color band covers the entire hue spectrum (from red to purple), and each successive color band gets a little darker (from light red - light purple in the first band, to dark red - dark purple in the last band) by lowering the saturation or value. This sounds weird, but is effective.
Comparison of the playroom scene: …
=> MCS-1315 Trying to improve visibility of debug depth images.

machine_common_sense/logging_config.py, tests/test_logging_config.py
This affects other libraries that use python logging.  I was getting some log from matlabplot on the debug level that I didn't want.  I seem to still be getting a print statement from them when i use breakpoints, but I can live with that.:
`Backend TkAgg is interactive backend. Turning interactive mode on.`
=> Changed logging config to set root level logging higher and configurable

machine_common_sense/controller_events.py, machine_common_sense/history_writer.py, tests/test_history_event_handler.py
Adds data from step 0 (when the action is 'initialize' and no real commands have been sent)
=> MCS-1339 Added start data to scene history file

machine_common_sense/history_writer.py, machine_common_sense/scene_history.py, tests/test_history_event_handler.py
All, I have some more integration testing to do with the Jacobs branch, but wanted to get this in front of everyone.
=> MCS-1342: Add 'targetIsVisibleAtStart' to first object in history

machine_common_sense/plotter.py
This was causing the top down plotter to fail on intuitive physics scenes.  I'm not sure if they are important in that case, but they shouldn't throw exceptions.
=> found and fixed a vector3d that didn't get fixed from the pydantic change

docs/source/remotely.rst
These instructions seemed a little stale. Notably, there was no information on running `cache_addressables` using `DISPLAY:=0`. Additionally, the "Remote Run Test Script" used an action that's no longer available. I cleaned up a few of the comments as well.
I think we should wait to finalize this PR until after the eval. Other folks can add documentation they think would be useful to make available for the TA1s.
=> Updating the instructions for running remotely.

machine_common_sense/config_manager.py, tests/test_config_manager.py
The `resetCenterOfMass` property was added to address visual behavior when the object hit the ground that the TA2 psychs deemed undesirable. Its intent was to reset the implausible center of mass (back to the object's normal center of mass) when the object first gained an upward velocity due to hitting and bouncing off the floor. The issue exposed during Eval 5 was that sometimes affected objects would bounce when initially placed on the visible support, causing their center of mass to be reset too soon. Therefore I've now added a `resetCenterOfMassAtY` property, replacing the previous behavior, which only resets the center of mass when the object falls past a specified Y position. As a fallback, in case this approach doesn't work for whatever reason, we can remove `resetCenterOfMass` …
=> MCS-1433 Added resetCenterOfMassAtY object schema property.

.github/workflows/ci.yaml
Compared logs, figured out it was this requirementslib dependency causing the issue. Also removed the requirementsFiles lines from the isort step, since it looks redundant (we already download our requirements.txt by that point) and it only seems to use the first file listed anyway from what I can tell. 
Tried this out on the depth map test branch, but decided to make a separate PR anyway.
=> MCS-1458 - Fixing dependency in ci.yaml

docs/source/dev.rst, machine_common_sense/config_manager.py, machine_common_sense/controller.py, requirements.txt, tests/test_config_manager.py
Uses instances of threading.Timer to check if we've been at the same step for x seconds (default is two hours). If so, end scene is called + an exception is thrown on the main thread. Added timeout value to the mcs config in case we need to change the length of time later.
=> MCS-1045 Added timeout for long scenes

machine_common_sense/config_manager.py, machine_common_sense/controller_media.py, machine_common_sense/controller_output_handler.py, machine_common_sense/goal_metadata.py, machine_common_sense/history_writer.py, machine_common_sense/plotter.py, machine_common_sense/reward.py, tests/test_config_manager.py, tests/test_controller_output_handler.py, tests/test_history_writer.py, tests/test_plotter.py, tests/test_reward.py
My initial version of the implementation. Happy to have a team discussion and adjust this approach if we decide it's not ideal.
1. There's now a goal `category` called "multi retrieval", which is distinct from normal "retrieval". This seemed better to me than adding a new/separate boolean property.
2. The `metadata` in the "multi retrieval" goals will have a `targets` property, that's a list of target dicts, rather than a single `target` dict. Like the single `target` dict, each dict will have an `id` corresponding to the target's "id". This seemed better than trying to reuse `target`, but making it sometimes a dict, and sometimes a list.
3. Added code to make sure the `targets` are handled properly, including clearing them when not running at oracle metadata level.
4. As discussed this …
=> MCS-895 Initial version of handling scenes with multiple targets.

machine_common_sense/reward.py
If the goal_objects was an empty array and there was a goal id in the metadata object, it would say the reward was achieved, it appears that the only test this covered was 094.
=> MCS-1542: Fix case where an empty goal_objects would give the goal reward achieved

integration_tests/run_handmade_tests.py
The final integration test (186) uses a custom MCS config file, but the MCS config wasn't being reset before the "additional tests" were run.
You can reproduce the issue using (you should see an IndexError on `development`, but not on here):
```
python integration_tests/run_handmade_tests.py --mcs_unity_version development --ignore 0,10,11,12,13,14,15,16,17,180,181,182,183,184,185 --metadata oracle
```
This ignore all the tests except the final one (186) and the "additional tests".
=> Fix Jenkins Build (Jan 16 2023)

integration_tests/data/193.multi_retrieval_pickup_number.actions.txt, integration_tests/data/193.multi_retrieval_pickup_number.level1.outputs.json, integration_tests/data/193.multi_retrieval_pickup_number.level2.outputs.json, integration_tests/data/193.multi_retrieval_pickup_number.oracle.outputs.json, integration_tests/data/193.multi_retrieval_pickup_number.scene.json, integration_tests/data/194.multi_retrieval_pickup_number_two.actions.txt, integration_tests/data/194.multi_retrieval_pickup_number_two.level1.outputs.json, integration_tests/data/194.multi_retrieval_pickup_number_two.level2.outputs.json, integration_tests/data/194.multi_retrieval_pickup_number_two.oracle.outputs.json, integration_tests/data/194.multi_retrieval_pickup_number_two.scene.json, integration_tests/data/195.multi_retrieval_drop.actions.txt, integration_tests/data/195.multi_retrieval_drop.level1.outputs.json, integration_tests/data/195.multi_retrieval_drop.level2.outputs.json, integration_tests/data/195.multi_retrieval_drop.oracle.outputs.json, integration_tests/data/195.multi_retrieval_drop.scene.json, integration_tests/data/196.multi_retrieval_pickup_number_drop.actions.txt, integration_tests/data/196.multi_retrieval_pickup_number_drop.level1.outputs.json, integration_tests/data/196.multi_retrieval_pickup_number_drop.level2.outputs.json, integration_tests/data/196.multi_retrieval_pickup_number_drop.oracle.outputs.json, integration_tests/data/196.multi_retrieval_pickup_number_drop.scene.json, machine_common_sense/reward.py, tests/test_controller.py, tests/test_controller_output_handler.py, tests/test_reward.py
Throwing this up here for discussion. I believe we've done this in the past where we've "patched" TA1 EC2 instances by overwriting specific files (in this case, `reward.py`) that have been downloaded in their local python virtual environment.
Changes:
- Added an optional "pickup_number" property to the goal metadata. If a scene's goal has a "pickup_number", that's the number of targets which must be picked up in order to attain the reward. Therefore in ambiguous Number Comparison and Arithmetic scenes, we can label ALL soccer balls as "targets", but have the "pickup_number" be half of the total.
- Scenes without a "pickup_number" should still work as before: all of the "targets" must be picked up in order to attain the reward.
TODOs:
- Add an integration test as part of this PR.
- Update …
=> MCS-1707 Added optional pickup_number property in goal metadata for multi-retrieval reward calculations of ambiguous scenes.

machine_common_sense/controller.py
This functionality probably needs more of an overhaul post-evaluation, but figured it doesn't hurt to at least update the log message + level for now. Note that there are some auto formatting fixes as well.
=> Update step timeout log message for clarity (MCS-1760).

docs/source/schema.rst
This is the page that gets deployed to: https://nextcenturycorporation.github.io/MCS/schema.html
You can build the docs locally by running `make html` in the `docs` folder.
I didn't bother adding the tools with the novel materials, since we're planning on changing how we do that anyway.
Also fixed a couple of typos.
=> MCS-1732 Updated schema with novel types from Eval 6.

.github/workflows/docs-publish.yaml, docs/requirements.txt, docs/source/requirements.txt
Fixes to for Doc Publish (hot fixed on master to get release deployed)
Looks like deploy has gone through successfully.  There will be errors with the PYPI push since that was successful the first time, subsequent workflow runs (since doc-publish and pypi push are part of the same workflow) show the PYPI fails because it already exists.
=> MCS-1869 Fixes for Doc Publish

machine_common_sense/action.py, machine_common_sense/scripts/run_human_input.py
This was originally a webenabled ticket to enable the "spacebar = Pass" action, but I realized the problem was actually in human input mode:
1.) The spacebar was being used as a shortcut for two different actions (Pass and EndScene)
2.) Input in human input mode is stripped, so the spacebar didn't actually do anything.
This should be fixed now + can be tested in human input mode (spacebar will now pass, "q" to EndScene).
=> MCS-1808 - Fix shortcut keys for Pass and EndScene in human input mode 

webenabled/templates/mcs_page.html
For webenabled: if you pressed the keys too fast, the images would get out of sync and sometimes not load properly. I went with the option of ignoring extra keypresses if an action was currently being processed.
=> MCS-1807 - [Webenabled] Avoid getting out of sync images with quick keypresses

webenabled/mcs_interface.py, webenabled/run_scene_with_dir.py, webenabled/templates/mcs_page.html
This was to slightly improve the experience of when the user has an unexpected error from the Unity app. The main things I tested were:
- invalid actions (i.e. only available action is "Pass" but I tried "MoveAhead")
- trying an action when the unity app is no longer running
There should be an error displayed in these cases instead of return status (and an error file saved in the output folder).
=> MCS-1910 [Webenabled] error handling

webenabled/templates/mcs_page.html
Ended up being a very small PR.
I'll add a comment on this ticket, but originally this was to localize this fetch.js dependency for when we package things up (which is why I branched off of the pyinstaller branch). The fetch.js script is a polyfill for older browsers that don't have the fetch API, but upon further investigation, this fetch.js script (which is also a really old version) would likely not even work correctly without an additional promise polyfill + we've never had to worry about older browsers like IE 7 before anyway, so I figured I'd just go ahead and remove it.
=> MCS-1931 - [Webenabled] Remove fetch.js

webenabled/templates/mcs_page.html
Original ticket was to not submit a pass action for function keys -- decided to simply ignore all non-action keys. Also addressed a small bug where you could submit an action before actually choosing a scene. 
Note that this is branched off of MCS-1816-styling.
=> MCS-1925 - [Webenabled] Ignoring non-action keys

machine_common_sense/config_manager.py
See Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/341
=> MCS-1908 Added isometric_front_right scene property for Eval 7 NYU tasks.

webenabled/mcsweb.py, webenabled/templates/mcs_page.html
This is to prevent multiple dangling controller processes in webenabled. You should be able to still have multiple sessions across browsers, but now it'll be restricted to one session/controller per browser. If you are in the same browser and try to open up webenabled in another tab, you should get a warning/error message.
=> MCS-1945 [Webenabled] Restrict to one tab

docs/source/install.rst, integration_tests/run_handmade_tests.py, machine_common_sense/__init__.py, machine_common_sense/config_manager.py, machine_common_sense/controller.py, machine_common_sense/import_override.py, requirements.txt, tests/test_config_manager.py, tests/test_recorder.py
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/345
These changes would make Phi's PR obsolete: https://github.com/NextCenturyCorporation/ai2thor/pull/343
There are some spicy changes here, and I'm happy to discuss the pros and cons further.
I've tested this on both Windows and Linux.
For Windows:
- (On Linux) Build the Unity app for Windows, using the correct Unity feature branch (switching the Target Platform may cause the Unity Editor to think for a while)
- Move the Unity app onto your Windows machine
- (On Windows) Clone the MCS git repo, checkout this feature branch, and setup your virtual environment (install python dependencies, etc.)
- (On Windows) Optionally, run `cache_addressables`
- (On Windows) Try `run_in_human_input_mode` with the …
=> MCS-1963 Updates to Support Windows

integration_tests/data/107.lava.oracle.outputs.json, integration_tests/data/119.lava_end_scene.oracle.outputs.json
Updated output for failing test.. Reran integration for both Windows and Linux builds/addressables.   Looks like the int tests are all good (change .5 to .51 which is now passes the math.isclose check).
=> MCS-1976 - Fix integration test for windows

webenabled/mcs_interface.py, webenabled/mcsweb.py, webenabled/run_scene_with_dir.py, webenabled/templates/mcs_page.html
- Now shows a sideways-scrolling list of small images from the latest 500 actions (see comment)
- Added "quick action" buttons to run multiple actions in a row and watch results as they become available
- Renamed "Keyboard Shortcuts" to "Usage" and added a "Notes" section
- Minor styling tweaks and bug fixes
=> MCS-1923 MCS-1924 Webenabled Updates: Previous Images, Quick Actions

webenabled/mcs_interface.py, webenabled/templates/mcs_page.html
My solution for this was just to wait for less time in the case of an instant error. Also fixed a minor bug with the quick action buttons.
=> MCS-1982 - [Webenabled] Attempting Unavailable Action Waits until Timeout

webenabled/templates/mcs_page.html
The quick action of turn 9 still turns the camera ~90 degrees.
=> MCS - 2014 - Set Rotation from 36 to 9
